#!/usr/bin/env node
/**
 * ===========================================================
 *  SUKUNA MD — Universal Bootstrap (works on Panel & Website)
 * ===========================================================
 *
 *  Usage:
 *    1) Fill in the CONFIG block below.
 *    2) Run:  node index.js
 *
 *  This script will:
 *    - git clone https://github.com/pasquawisdom2007-beep/SUKUNA_MD
 *    - write your config.js + .env into the cloned folder
 *    - npm install
 *    - npm start
 *
 *  Get a SESSION_ID from: https://pair-site-91ob.onrender.com/
 *  (Optional — leave blank to use the pairing-code flow instead.)
 * ===========================================================
 */

// ====================== FILL THIS IN =======================
const CONFIG = {
  ownerNumber: '',              // e.g. '2349127857212'  (country code, NO +)
  pairNumber:  '',              // number to pair  e.g. '2349127857212'
  prefix:      '.',             // command prefix
  mode:        'public',        // 'public' | 'private'
  botName:     'SUKUNA MD',
  sessionId:   '',              // optional — paste from pair-site to skip pairing
};
// ===========================================================

const { spawn, spawnSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const REPO    = 'https://github.com/pasquawisdom2007-beep/SUKUNA_MD';
const BOT_DIR = path.join(__dirname, 'SUKUNA_MD');

const c = {
  r: (s) => `\x1b[31m${s}\x1b[0m`,
  g: (s) => `\x1b[32m${s}\x1b[0m`,
  y: (s) => `\x1b[33m${s}\x1b[0m`,
  c: (s) => `\x1b[36m${s}\x1b[0m`,
};

function log(tag, msg)  { console.log(`${c.c('[' + tag + ']')} ${msg}`); }
function die(msg)       { console.error(c.r('[FATAL] ') + msg); process.exit(1); }

function run(cmd, args, opts = {}) {
  log('RUN', `${cmd} ${args.join(' ')}`);
  const res = spawnSync(cmd, args, { stdio: 'inherit', shell: process.platform === 'win32', ...opts });
  if (res.status !== 0) die(`${cmd} ${args.join(' ')} → exit ${res.status}`);
}

// ---------- 1. validate ----------
function validate() {
  const sanitize = (v) => String(v || '').replace(/[^0-9]/g, '');
  CONFIG.ownerNumber = sanitize(CONFIG.ownerNumber);
  CONFIG.pairNumber  = sanitize(CONFIG.pairNumber);

  if (!CONFIG.ownerNumber || CONFIG.ownerNumber.length < 8)
    die('CONFIG.ownerNumber is required (digits only, with country code).');
  if (!CONFIG.pairNumber || CONFIG.pairNumber.length < 8)
    die('CONFIG.pairNumber is required (digits only, with country code).');
  if (!['public', 'private'].includes(CONFIG.mode))
    die("CONFIG.mode must be 'public' or 'private'.");
}

// ---------- 2. clone / pull ----------
function fetchRepo() {
  if (fs.existsSync(BOT_DIR)) {
    log('GIT', 'Repo already cloned → pulling latest...');
    run('git', ['-C', BOT_DIR, 'pull', '--ff-only']);
  } else {
    log('GIT', `Cloning ${REPO} ...`);
    run('git', ['clone', '--depth', '1', REPO, BOT_DIR]);
  }
}

// ---------- 3. write config.js + .env ----------
function writeConfig() {
  const env =
`OWNER_NUMBER=${CONFIG.ownerNumber}
PAIR_NUMBER=${CONFIG.pairNumber}
BOT_PREFIX=${CONFIG.prefix}
BOT_MODE=${CONFIG.mode}
BOT_NAME=${CONFIG.botName}
`;
  fs.writeFileSync(path.join(BOT_DIR, '.env'), env);
  log('CFG', 'Wrote .env');

  const cfg =
`/**
 * SUKUNA MD — generated by bootstrap index.js
 * Edit the top-level bootstrap and re-run to change these values.
 */
module.exports = {
    botName: process.env.BOT_NAME    || ${JSON.stringify(CONFIG.botName)},
    version: '3.0.0',
    prefix:  process.env.BOT_PREFIX  || ${JSON.stringify(CONFIG.prefix)},
    mode:    process.env.BOT_MODE    || ${JSON.stringify(CONFIG.mode)},

    assets: {
        menuVideo: './assets/menuvideo.mp4',
        menuThumb: './assets/menuthumb.jpg'
    },

    ownerNumber: process.env.OWNER_NUMBER || ${JSON.stringify(CONFIG.ownerNumber)},
    pairNumber:  process.env.PAIR_NUMBER  || ${JSON.stringify(CONFIG.pairNumber)},

    owner: {
        name:    'OWNER',
        number:  process.env.OWNER_NUMBER || ${JSON.stringify(CONFIG.ownerNumber)},
        github:  'https://github.com/pasquawisdom2007-beep/SUKUNA_MD',
        channel: 'https://whatsapp.com/channel/0029VbCJho147XeEEuR1LA3s'
    },

    sessionId: ${JSON.stringify(CONFIG.sessionId || '')},

    sessions: {
        folder: './sessions/',
        autoReconnect: true
    },

    groupDefaults: {
        antilink: false, antilinkAction: 'delete',
        antimention: false, antimentionMode: 'normal',
        antimentionAction: 'warn', antimentionMax: 5,
        welcome: false, welcomeMessage: '👋 Welcome @user to @group!',
        goodbye: false, goodbyeMessage: '👋 Goodbye @user!',
        mute: false
    },

    apiKeys: {
        openai:  process.env.OPENAI_API_KEY  || '',
        weather: process.env.WEATHER_API_KEY || ''
    },

    messages: {
        wait: '⏳ Processing...',
        success: '✅ Success!',
        error: '❌ Error occurred!',
        adminOnly: '🛡️ This command is only for admins!',
        groupOnly: '👥 This command can only be used in groups!',
        botAdminNeeded: '🤖 Bot needs to be admin to execute this command!'
    }
};
`;
  fs.writeFileSync(path.join(BOT_DIR, 'config.js'), cfg);
  log('CFG', 'Wrote config.js');
}

// ---------- 4. session id from pair-site (optional) ----------
function writeSession() {
  if (!CONFIG.sessionId) return;
  const dir  = path.join(BOT_DIR, 'sessions', CONFIG.pairNumber);
  const file = path.join(dir, 'creds.json');
  if (fs.existsSync(file)) {
    log('SESS', 'creds.json already exists — leaving as-is.');
    return;
  }
  fs.mkdirSync(dir, { recursive: true });

  let raw = CONFIG.sessionId.trim();
  // strip common prefixes some pair-sites add (e.g. "SUKUNA~", "PASQUA~")
  if (raw.includes('~')) raw = raw.split('~').slice(1).join('~');

  let creds;
  try {
    // Try base64 first, then plain JSON
    try { creds = JSON.parse(Buffer.from(raw, 'base64').toString('utf-8')); }
    catch { creds = JSON.parse(raw); }
  } catch (e) {
    die('CONFIG.sessionId is not a valid session string (expected base64 or JSON).');
  }
  fs.writeFileSync(file, JSON.stringify(creds, null, 2));
  log('SESS', `Session written → sessions/${CONFIG.pairNumber}/creds.json`);
}

// ---------- 5. install ----------
function install() {
  if (fs.existsSync(path.join(BOT_DIR, 'node_modules'))) {
    log('NPM', 'node_modules already present — skipping install.');
    return;
  }
  log('NPM', 'Installing dependencies (this can take a few minutes)...');
  run('npm', ['install', '--omit=dev', '--no-audit', '--no-fund'], { cwd: BOT_DIR });
}

// ---------- 6. start ----------
function start() {
  log('BOT', 'Starting SUKUNA MD...\n');
  const child = spawn('npm', ['start'], {
    cwd: BOT_DIR,
    stdio: 'inherit',
    shell: process.platform === 'win32',
    env: { ...process.env,
      OWNER_NUMBER: CONFIG.ownerNumber,
      PAIR_NUMBER:  CONFIG.pairNumber,
      BOT_PREFIX:   CONFIG.prefix,
      BOT_MODE:     CONFIG.mode,
      BOT_NAME:     CONFIG.botName,
    },
  });

  const forward = (sig) => () => { if (!child.killed) child.kill(sig); };
  process.on('SIGINT',  forward('SIGINT'));
  process.on('SIGTERM', forward('SIGTERM'));
  child.on('exit', (code) => process.exit(code ?? 0));
}

// ---------- main ----------
(function main() {
  console.log(c.r(`
╔════════════════════════════════════════════════════════════════╗
║              SUKUNA MD — Universal Bootstrap                   ║
║        Panel  •  Website  •  VPS  •  Termux  •  Render         ║
╚════════════════════════════════════════════════════════════════╝
`));
  validate();
  fetchRepo();
  writeConfig();
  writeSession();
  install();
  start();
})();
