/**
 * .generate <prompt> — AI image generation
 *
 * Uses prexzyvilla DALL·E API as primary, falls back to the realistic
 * model if the first one fails or returns no image.
 *
 * Aliases: .gen, .img
 */
const axios = require('axios');

const PRIMARY = 'https://apis.prexzyvilla.site/ai/dalle';
const FALLBACK = 'https://apis.prexzyvilla.site/ai/realistic';

async function fetchImageUrl(endpoint, prompt) {
    try {
        const { data } = await axios.get(endpoint, {
            params: { prompt },
            timeout: 60000,
        });
        if (!data || data.status !== true) return null;
        // DALL·E shape: data.image_url[0].image.url
        // Realistic shape may be similar OR data.result / data.url — handle all.
        const arr = data.image_url || data.images || data.result;
        if (Array.isArray(arr) && arr.length) {
            const first = arr[0];
            return first?.image?.url || first?.url || (typeof first === 'string' ? first : null);
        }
        if (typeof data.result === 'string') return data.result;
        if (typeof data.url === 'string') return data.url;
        return null;
    } catch (e) {
        console.error(`[generate] ${endpoint} failed:`, e.message);
        return null;
    }
}

async function downloadImage(url) {
    try {
        const res = await axios.get(url, { responseType: 'arraybuffer', timeout: 60000 });
        const buf = Buffer.from(res.data);
        if (!buf || buf.length < 1024) return null;
        return buf;
    } catch (e) {
        console.error('[generate] download failed:', e.message);
        return null;
    }
}

module.exports = {
    name: 'generate',
    aliases: ['gen', 'img'],
    description: 'Generate an AI image from text (.generate <prompt>)',
    category: 'ai',

    async execute({ sock, msg, from, reply, args }) {
        if (!args.length) {
            return reply(
                `🎨 *AI Image Generator*\n\n` +
                `Usage: .generate <description>\n` +
                `Example: .generate a cat wearing a spacesuit on the moon`
            );
        }

        const prompt = args.join(' ').trim();
        await reply('🎨 *Generating image...* please wait.');

        // Try primary, then fallback.
        let imgUrl = await fetchImageUrl(PRIMARY, prompt);
        let modelUsed = 'DALL·E 3 XL';
        if (!imgUrl) {
            imgUrl = await fetchImageUrl(FALLBACK, prompt);
            modelUsed = 'Realistic';
        }

        if (!imgUrl) {
            return reply('❌ Both image generators failed. Please try again with a different prompt.');
        }

        // Download the image to a buffer (the upstream URLs are temporary).
        const buf = await downloadImage(imgUrl);
        if (!buf) {
            return reply('❌ Generated image could not be downloaded. Try again.');
        }

        try {
            await sock.sendMessage(from, {
                image: buf,
                caption: `🎨 *AI Generated Image*\n\nPrompt: ${prompt}\nModel: ${modelUsed}\n\n> Generated by SUKUNA MD`
            }, { quoted: msg });
        } catch (err) {
            reply(`❌ Failed to send image: ${err.message}`);
        }
    }
};
