/**
 * Imagine Command — Generate AI images
 * Usage: .imagine <prompt>
 */

module.exports = {
    name: 'imagine',
    aliases: ['aiimage', 'genimage', 'create'],
    description: 'Generate AI images from text',
    category: 'ai',
    async execute({ sock, msg, from, reply, args }) {
        if (!args.length) {
            return reply(
                `🎨 *AI Image Generator*\n\n` +
                `Usage: .imagine <description>\n` +
                `Example: .imagine a cat wearing a spacesuit on the moon`
            );
        }

        const prompt = args.join(' ');
        
        try {
            await reply('🎨 *Generating image...*\nThis may take a moment.');
            
            const encodedPrompt = encodeURIComponent(prompt);
            const imageUrl = `https://api.lolhuman.xyz/api/imagine?apikey=free&prompt=${encodedPrompt}`;
            
            await sock.sendMessage(from, {
                image: { url: imageUrl },
                caption: `🎨 *AI Generated Image*\n\nPrompt: ${prompt}\n\n> Generated by SUKUNA MD`
            }, { quoted: msg });
        } catch (err) {
            reply('❌ Failed to generate image. Please try a different prompt.');
        }
    }
};
